# GitHub Copilot Setup Steps for xAPI Java
# This file configures the environment for GitHub Copilot agents working on this repository.
# See: https://docs.github.com/en/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

steps:
  # Step 1: Set up Java 25 using the setup-java action
  - name: Set up JDK 25
    uses: actions/setup-java@v5
    with:
      java-version: "25"
      distribution: "temurin"
      cache: maven
    notes: |
      Sets up Java 25 (Temurin distribution) for the build environment.
      
      This uses the same approach as the project's CI/CD workflows (maven_push.yml, maven_pull_request.yml).
      The 'cache: maven' option automatically caches Maven dependencies in ~/.m2/repository
      to speed up subsequent builds.
      
      Java 25 or newer is required for this project as specified in pom.xml.

  # Step 2: Build with Maven to verify environment
  - name: Build with Maven
    shell: bash
    run: |
      # Build and download dependencies, skip tests for faster setup
      ./mvnw -B clean verify -DskipTests --file pom.xml
    notes: |
      Runs a Maven build to verify the environment and download dependencies.
      Tests and integration tests are skipped during setup for faster execution.
      Tests can be run later as needed.
      
      The -B flag runs Maven in batch (non-interactive) mode.
      The -DskipTests flag skips both unit tests and integration tests.
      
      Build process includes:
      - CheckStyle validation (Google Java Style Guide)
      - Compilation of all modules (xapi-model, xapi-client, samples, xapi-model-spring-boot-starter)
      - Dependency resolution and caching
      
      Expected duration: 1-2 minutes on first run, faster with cached dependencies.
      
      Key dependencies automatically downloaded and cached:
      - Spring Boot 3.5.7
      - Spring WebClient (reactive)
      - Jackson (JSON serialization)
      - Lombok (code generation)
      - JUnit 5 (testing)
      - Hamcrest (assertions)
      - OkHttp (HTTP client for testing)
      - CheckStyle (code style enforcement)
      
      Troubleshooting:
      - If build fails with "release version 25 not supported", the Java setup may have failed
      - If dependencies fail to download, check network connectivity
      - If CheckStyle fails, there may be code style violations
