# GitHub Copilot Setup Steps for xAPI Java
# This file configures the environment for GitHub Copilot agents working on this repository.
# See: https://docs.github.com/en/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

steps:
  # Step 1: Set up Java 25 using the setup-java action
  - name: Set up JDK 25
    uses: actions/setup-java@v5
    with:
      java-version: "25"
      distribution: "temurin"
      cache: maven
    notes: |
      Sets up Java 25 (Temurin distribution) for the build environment.
      
      This uses the same approach as the project's CI/CD workflows (maven_push.yml, maven_pull_request.yml).
      The 'cache: maven' option automatically caches Maven dependencies in ~/.m2/repository
      to speed up subsequent builds.
      
      Java 25 or newer is required for this project as specified in pom.xml.

  # Step 2: Build with Maven to verify environment
  - name: Build with Maven
    shell: bash
    run: |
      # Run a full build with tests to verify everything works
      ./mvnw -B clean verify --file pom.xml
    notes: |
      Runs a full Maven build including CheckStyle validation and all tests.
      The -B flag runs Maven in batch (non-interactive) mode.
      
      Build process includes:
      - CheckStyle validation (Google Java Style Guide)
      - Compilation of all modules (xapi-model, xapi-client, samples, xapi-model-spring-boot-starter)
      - Unit tests (300+ tests)
      - Integration tests
      - Code coverage analysis (JaCoCo)
      
      Expected duration: 2-3 minutes on first run, faster with cached dependencies.
      
      Key dependencies automatically downloaded and cached:
      - Spring Boot 3.5.7
      - Spring WebClient (reactive)
      - Jackson (JSON serialization)
      - Lombok (code generation)
      - JUnit 5 (testing)
      - Hamcrest (assertions)
      - OkHttp (HTTP client for testing)
      - CheckStyle (code style enforcement)
      
      Troubleshooting:
      - If build fails with "release version 25 not supported", the Java setup may have failed
      - If dependencies fail to download, check network connectivity
      - If tests fail, this may indicate an environment-specific issue
