name: Chore
description: Create a chore issue for maintenance and housekeeping tasks
title: "[Chore]: "
labels: ["chore", "triage"]
assignees:
  - knoake
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this chore issue!
  - type: textarea
    id: what
    attributes:
      label: What
      description: What does the chore involve?
      placeholder: Update dependencies, refactor code, clean up documentation...
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why
      description: Why is this chore necessary?
      placeholder: To improve maintainability, reduce technical debt, keep dependencies up-to-date...
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional information or context about the chore.
      placeholder: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
